### ISSUE TITLE
HLmapData_new

### ISSUE THREAD

**Issue by DHouldershaw** [kiharalab/EM-GAN#2]
Hi,
 Just trying to follow your tutorial, as detailed in README.md, and falling at the first step. The data_prep/HLmapData_new binary in the distribution seems to be  a different version ? On running it returns:-
./data_prep/HLmapData_new
Usage: MLmapData -a [MAP1.mrc] -b [MAP2.mrc] [(option)]
v1.10	
---Options---
-A [float] : Density threhold value for MAP1 def=0
-B [float] : Density threhold value for MAP2 def=0
-w [int  ] : Size of voxel window def=5 (11*11*11) 
-s [int  ] : Step number [int] of the sliding voxel def=1
Thi is Ver 0.100

So, no -c flag which is in disagreement with the documentation in README.md.
Is there possibly a fix for this ?
Many Thanks for your help.

**Comment by SaiRagh4** [comment]
Hello

Thanks for trying the code out. The fix is in now. Could you please try it again.
Happy to help with any questions/concerns.

Sai
