### ISSUE TITLE
Failed the first step

### ISSUE THREAD

**Issue by HaowenGuan** [kiharalab/EM-GAN#4]
Can someone explain to me how to run the HLmapData file in the first step?
This file doesn't even have a suffix. I tried to run the code on both windows and MacOS system, but its all failed.
Also, This file doesn't seems like a executable file nor readable file. What is this file?

**Comment by SherryXiao689** [comment]
I am also failed in the first step, can anyone help to do this ? Thanks!

**Comment by SaiRagh4** [comment]
Hi,

I know its been a while but can you try re-running. We updated our README. Please open a new issue in case you see issues. Closing this for easier tracking.
